### ISSUE TITLE
`pre-commit autoupdate` downgrades to v0.6.1

### ISSUE THREAD

**Issue by JaapJoris** [biomejs/pre-commit#26]
Context:  https://github.com/biomejs/pre-commit/issues/7 added tags to make `pre-commit autoupdate` work. However, it doesn't. I'm not sure _why_ it doesn't but I'm creating a bug report anyway. My apologies if this failure is not on your end.

# Steps to reproduce

Follow [README.md](https://github.com/biomejs/pre-commit/blob/main/README.md) and add the following to `.pre-commit-config.yaml`:

```yaml
  - repo: https://github.com/biomejs/pre-commit
    rev: v1.9.4
    hooks:
      - id: biome-check
```

Then, run `pre-commit autoupdate`:

```shell
$ pre-commit autoupdate
[https://github.com/biomejs/pre-commit] updating v1.9.4 -> v0.6.1
```

# Expected outcome

The version is still v1.9.4:

```yaml
  - repo: https://github.com/biomejs/pre-commit
    rev: v1.9.4
    hooks:
      - id: biome-check
```

# Actual outcome

The version is now v0.6.1:

```yaml
  - repo: https://github.com/biomejs/pre-commit
    rev: v0.6.1
    hooks:
      - id: biome-check
```
