### ISSUE TITLE
`pre-commit autoupdate` downgrades `v2.0.0-beta.6` to `v2.0.0-beta.5` (and doesn't upgrade in another direction)

### ISSUE THREAD

**Issue by sterliakov** [biomejs/pre-commit#37]
Given this stripped down config

```yaml
repos:
  - repo: https://github.com/biomejs/pre-commit
    rev: v2.0.0-beta.5
    hooks:
      - id: biome-check
        args: [--max-diagnostics, '500']
```

The following happens:

```sh
$ pre-commit autoupdate
[https://github.com/biomejs/pre-commit] already up to date!
```

Manually replacing `beta.5` with `beta.6` causes the following:

```sh
$ pre-commit autoupdate
[https://github.com/biomejs/pre-commit] updating v2.0.0-beta.6 -> v2.0.0-beta.5
```
