### ISSUE TITLE
cannot use biome ci with `--config-path` cli arg

### ISSUE THREAD

**Issue by cemysf** [biomejs/pre-commit#9]
Trying to use this config path cli arg, defined [here](https://biomejs.dev/reference/cli/#biome-ci)
```
  - repo: https://github.com/biomejs/pre-commit
    rev: v0.5.0
    hooks:
    - id: biome-ci
      args: ["--config-path", "frontend/biome.jsonc"]
      additional_dependencies: ["@biomejs/biome@1.4.1"]
```

Result:
```
biome ci.................................................................Failed
- hook id: biome-ci
- exit code: 1

frontend/biome.jsonc/rome.json internalError/fs ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Biome couldn't read the file
  
  ✖ Biome couldn't read the following file, maybe for permissions reasons or it doesn't exists: frontend/biome.jsonc/rome.json
  
```
